"""
Users and Authentication Router
================================
This module configures authentication and user management using FastAPI Users.

Provides:
- JWT token authentication
- Cookie-based authentication
- User registration
- Password reset
- Email verification
- User CRUD operations

All authentication endpoints are automatically generated by FastAPI Users
based on the configured backends and routers.
"""

import uuid
from fastapi import Depends, Request, APIRouter
from typing import Optional
from fastapi_users import BaseUserManager, FastAPIUsers, UUIDIDMixin
from fastapi_users.authentication.strategy.db import AccessTokenDatabase, DatabaseStrategy
from fastapi_users.authentication import AuthenticationBackend, BearerTransport, JWTStrategy, CookieTransport
from app.models import UserUpdate, UserRead

from app.models import UserCreate
from app.database import AccessToken, get_access_token_db, User, get_user_db
import os

# ============================================================================
# Authentication Configuration
# ============================================================================
# Secret key for token signing (should be kept secure in production)
SECRET = os.environ['SECRET']

# Cookie transport for browser-based authentication
cookie_transport = CookieTransport(cookie_max_age=3600)  # 1 hour cookie lifetime

# Bearer token transport for API authentication
bearer_transport = BearerTransport(tokenUrl="auth/jwt/login")


def get_jwt_strategy() -> JWTStrategy:
    """
    Create JWT authentication strategy.
    Note: Currently not used, but available for future JWT implementation.
    """
    return JWTStrategy(secret=SECRET, lifetime_seconds=3600)


def get_database_strategy(
    access_token_db: AccessTokenDatabase[AccessToken] = Depends(get_access_token_db),
) -> DatabaseStrategy:
    """
    Create database-based authentication strategy.
    Uses access tokens stored in the database for authentication.
    
    Args:
        access_token_db: Access token database adapter
    
    Returns:
        DatabaseStrategy instance with 1 hour token lifetime
    """
    return DatabaseStrategy(access_token_db, lifetime_seconds=3600)


# ============================================================================
# Authentication Backends
# ============================================================================
# Configure authentication backends for different use cases:
# - JWT: For API clients (mobile apps, external services)
# - Cookie: For web browsers (frontend applications)

jwt_auth_backend = AuthenticationBackend(
    name="jwt",
    transport=bearer_transport,
    get_strategy=get_database_strategy,  # Uses database tokens, not pure JWT
)
cookie_auth_backend = AuthenticationBackend(
    name="cookie",
    transport=cookie_transport,
    get_strategy=get_database_strategy,
)


# ============================================================================
# User Manager
# ============================================================================
# Custom user manager that handles user lifecycle events.
# Extends FastAPI Users base manager with UUID-based user IDs.
class UserManager(UUIDIDMixin, BaseUserManager[User, uuid.UUID]):
    reset_password_token_secret = SECRET
    verification_token_secret = SECRET

    async def on_after_register(self, user: User, request: Optional[Request] = None):
        """Called after a user successfully registers."""
        print(f"User {user.id} has registered.")

    async def on_after_forgot_password(
        self, user: User, token: str, request: Optional[Request] = None
    ):
        """Called when a user requests a password reset."""
        print(f"User {user.id} has forgot their password. Reset token: {token}")

    async def on_after_request_verify(
        self, user: User, token: str, request: Optional[Request] = None
    ):
        """Called when a user requests email verification."""
        print(f"Verification requested for user {user.id}. Verification token: {token}")


async def get_user_manager(user_db=Depends(get_user_db)):
    """
    Dependency function that provides a user manager instance.
    Required by FastAPI Users.
    """
    yield UserManager(user_db)


# ============================================================================
# FastAPI Users Instance
# ============================================================================
# Main FastAPI Users instance that provides all authentication functionality.
fastapi_users = FastAPIUsers[User, uuid.UUID](
    get_user_manager,
    [cookie_auth_backend, jwt_auth_backend],  # Both backends enabled
)

# Create router for authentication and user endpoints
router = APIRouter()
# ============================================================================
# Register Authentication Routers
# ============================================================================
# Include all authentication and user management endpoints generated by
# FastAPI Users. These provide login, logout, registration, etc.

# JWT authentication endpoints (for API clients)
router.include_router(
    fastapi_users.get_auth_router(jwt_auth_backend),
    prefix="/auth/jwt",
    tags=["auth"],
)
# Cookie authentication endpoints (for web browsers)
router.include_router(
    fastapi_users.get_auth_router(cookie_auth_backend),
    prefix="/auth/cookie",
    tags=["auth"],
)
# User registration endpoint
router.include_router(
    fastapi_users.get_register_router(UserRead, UserCreate),
    prefix="/auth",
    tags=["auth"],
)
# Password reset endpoints
router.include_router(
    fastapi_users.get_reset_password_router(),
    prefix="/auth",
    tags=["auth"],
)
# Email verification endpoints
router.include_router(
    fastapi_users.get_verify_router(UserRead),
    prefix="/auth",
    tags=["auth"],
)
# User CRUD endpoints (get, update current user)
router.include_router(
    fastapi_users.get_users_router(UserRead, UserUpdate),
    prefix="/users",
    tags=["users"],
)


# ============================================================================
# Custom Backend Selection (Optional)
# ============================================================================
# Uncomment to implement custom logic for selecting authentication backends
# based on request path or other criteria.
# async def get_enabled_backends(request: Request):
#     """Return the enabled dependencies following custom logic."""
#     if request.url.path == "/protected-route-only-jwt":
#         return [jwt_auth_backend]
#     else:
#         return [cookie_auth_backend, jwt_auth_backend]

# ============================================================================
# Dependency for Getting Current User
# ============================================================================
# Use this dependency in route handlers to get the currently authenticated user.
# Example: user: User = Depends(current_active_user)
current_active_user = fastapi_users.current_user(active=True)

